window.thumbnails = [
    {
        id: 1,
        src: 'Images/Thumbnails/DSC1847.png',
        fullsizesrc:'Images/Images/Fullsize/DSC1847.jpg',
        fullsizesrc2:'Images/Images/Fullsize/DSC1944.jpg',
        alt: 'A thief came in the night',
        title: 'Western Wind',
        dateCreated: '01-03-23',
        inStock: true,
        length: '12"',
        width: '12"',
        area:144,
        retired: true,
        remakecustom: true,
        pricemultiplier: 1,
        featured: false,
        suggestedprice: 100,
        description: 'loren ipsum',
        type: 'normal'
    },
    {
        id: 2,
        src: 'Images/Thumbnails/DSC1930.png',
        fullsizesrc:'Images/Images/Fullsize/DSC1930.jpg',
        alt: 'A thief came in the night',
        title: 'Divergence',
        dateCreated: '01-01-23',
        inStock: false,
        width: '24"',
        length: '48"',
        area:1152,
        retired: false,
        remakecustom: true,
        pricemultiplier: 1,
        featured: false,
        suggestedprice: 200,
        description: 'loren ipsum',
        type: 'window_hanging'
    },
    {
        id: 3,
        src: 'Images/Thumbnails/DSC1942.png',
        fullsizesrc:'Images/Images/Fullsize/DSC1942.jpg',
        alt: 'A thief came in the night',
        title: 'Liminal Fountain',
        dateCreated: '01-01-23',
        inStock: false,
        width: '10"',
        length: '8"',
        area:80,
        retired: false,
        remakecustom: true,
        pricemultiplier: 1,
        featured: false,
        suggestedprice: 80,
        description: 'loren ipsum',
        type: 'normal'
    },
    {
        id: 4,
        src: 'Images/Thumbnails/DSC1943.png',
        fullsizesrc:'Images/Images/Fullsize/DSC1943.jpg',
        alt: 'A thief came in the night',
        title: 'Liminal Fountain',
        dateCreated: '01-01-23',
        inStock: false,
        width: '10"',
        length: '8"',
        area:80,
        retired: false,
        remakecustom: true,
        pricemultiplier: 1,
        featured: false,
        suggestedprice: 80,
        description: 'loren ipsum',
        type: 'normal'
    },
    {
        id: 5,
        src: 'Images/Thumbnails/Kayakertest.png',
        fullsizesrc:'Images/Images/Fullsize/DSC1948.jpg',
        alt: 'A thief came in the night',
        title: 'Kayaker',
        dateCreated: '09-16-26',
        inStock: true,
        length: '8"',
        width: '5"',
        area:40,
        retired: false,
        remakecustom: true,
        pricemultiplier: 1,
        featured: false,
        suggestedprice: 60,
        description: 'loren ipsum',
        type: 'normal'
    }
];
